// Auto-detected drone footage. The manifest is generated by
// scripts/generate-drone-manifest.mjs (runs on `predev` / `prebuild`).
// Drop a video in public/drone/ and it is re-encoded all-intra + picked up
// automatically.
import manifest from '@/lib/generated/drone-manifest.json';

// Fallback shown only if no video has been dropped into public/drone/ yet.
export const DRONE_FALLBACK_VIDEO =
  '/videos/green-fields-and-peaks.960x540.mp4';
export const DRONE_FALLBACK_FPS = 30;

export const DRONE_VIDEO_SRC: string = manifest.primary ?? DRONE_FALLBACK_VIDEO;
export const DRONE_FPS: number = manifest.fps ?? DRONE_FALLBACK_FPS;
